[build]
  command = "npm run build"
  functions = "functions"
  publish = "dist"

[dev]
  command = "npm run start"
  framework = "#custom"
  functions = "functions"
  publish = "dist"
  targetPort = 3000

[[headers]]
  # Define which paths this specific [[headers]] block will cover.
  for = "/assets/*.js"

  [headers.values]
    Content-Type = "text/javascript"