[build]
  command = "npm run build"
  functions = "functions"
  publish = "dist"

[dev]
  command = "npm run start"
  framework = "#custom"
  functions = "functions"
  publish = "dist"
  targetPort = 3000

[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "default-src *; font-src 'self'; img-src *; script-src 'self' 'unsafe-eval' 'unsafe-inline'; style-src 'self' 'unsafe-inline'; object-src 'none'; frame-ancestors 'none'"
    Referrer-Policy = "same-origin"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains"
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"

[[headers]]
  for = "/assets/*.js"

  [headers.values]
    Content-Type = "text/javascript"

[[redirects]]
  from = "/api/backup"
  to = "/.netlify/functions/backup"
  status = 200
  force = true

[[redirects]]
  from = "/api/omdb"
  to = "/.netlify/functions/omdb-get"
  status = 200
  force = true

[[redirects]]
  from = "/api/recommendations"
  to = "/.netlify/functions/tmdb-get-recs"
  status = 200
  force = true

[[redirects]]
  from = "/api/tmdb"
  to = "/.netlify/functions/tmdb-omdb-get"
  status = 200
  force = true

[[redirects]]
  from = "/api/user"
  to = "/.netlify/functions/user"
  status = 200
  force = true

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
  force = true
