@startuml "State Mgt. Dependencies"

'nodes
  'store
    node "vuex store" as store
    node app
    node explore
    node list
    node tools
    node user

  'module state
    node "app state" as astate
    node "explore state" as estate
    node "list state" as lstate
    node "tools state" as tstate
    node "user state" as ustate

  'module actions
    node "app actions" as aactions
    node "explore actions" as eactions
    node "list actions" as lactions
    node "tools actions" as tactions
    node "user actions" as uactions

'module hierarchy
  store -[dotted]->> app
  store -[dotted]->> explore
  store -[dotted]->> list
  store -[dotted]->> tools
  store -[dotted]->> user

  'state
    app -[#green;dashed]->> astate
    explore -[#green;dashed]->> estate
    list -[#green;dashed]->> lstate
    tools -[#green;dashed]->> tstate
    user -[#green;dashed]->> ustate

  'actions
    app -[#blue;dashed]->> aactions
    explore -[#blue;dashed]->> eactions
    list -[#blue;dashed]->> lactions
    tools -[#blue;dashed]->> tactions
    user -[#blue;dashed]->> uactions

'state mapping
  'app state
    astate -[#green;dashed]->> functions
    astate -[#green;dashed]->> toastMessage
    astate -[#green;dashed]->> windowOpen

  'explore state
    estate -[#green;dashed]->> recList
    estate -[#green;dashed]->> recSource

  'list state
    lstate -[#green;dashed]->> editTitleContent
    lstate -[#green;dashed]->> tracklist
    lstate -[#green;dashed]->> tracklistCache
    lstate -[#green;dashed]->> watchlist
    lstate -[#green;dashed]->> watchlistCache
    lstate -[#green;dashed]->> writeSuccess

  'tools state
    tstate -[#green;dashed]->> listSearchMode
    tstate -[#green;dashed]->> searchActive
    tstate -[#green;dashed]->> sortMode
    tstate -[#green;dashed]->> tracklistSorted
    tstate -[#green;dashed]->> watchlistSorted

  'user state
    ustate -[#green;dashed]->> currentUser
    ustate -[#green;dashed]->> GoTrueAuth
    ustate -[#green;dashed]->> userOptions

'actions mapping
  'app actions
    aactions -[#blue;dashed]->> closeAllModals
    aactions -[#blue;dashed]->> initialize
    aactions -[#blue;dashed]->> toggleWindow
    aactions -[#blue;dashed]->> sendToastMessage

  'explore actions
    eactions -[#blue;dashed]->> clearRecommendations
    eactions -[#blue;dashed]->> getRecommendations
    eactions -[#blue;dashed]->> initializeExplore
    eactions -[#blue;dashed]->> updateRecSource

  'list actions
    lactions -[#blue;dashed]->> clearEditTitle
    lactions -[#blue;dashed]->> deleteFromSearchResults
    lactions -[#blue;dashed]->> deleteItem
    lactions -[#blue;dashed]->> editListItem
    lactions -[#blue;dashed]->> initializeList
    lactions -[#blue;dashed]->> readList
    lactions -[#blue;dashed]->> selectEditTitle
    lactions -[#blue;dashed]->> toggleWriteSuccess
    lactions -[#blue;dashed]->> updateSearchResult
    lactions -[#blue;dashed]->> writeList

  'tools actions
    tactions -[#blue;dashed]->> initializeTools
    tactions -[#blue;dashed]->> resetList
    tactions -[#blue;dashed]->> searchList
    tactions -[#blue;dashed]->> sortList
    tactions -[#blue;dashed]->> updateSort

  'user actions
    uactions -[#blue;dashed]->> attemptConfirmation
    uactions -[#blue;dashed]->> attemptLogin
    uactions -[#blue;dashed]->> attemptLogout
    uactions -[#blue;dashed]->> attemptPasswordRecovery
    uactions -[#blue;dashed]->> attemptSignup
    uactions -[#blue;dashed]->> initAuth
    uactions -[#blue;dashed]->> initializeUser
    uactions -[#blue;dashed]->> processInvite
    uactions -[#blue;dashed]->> requestPasswordRecovery
    uactions -[#blue;dashed]->> updateUserAccount
    uactions -[#blue;dashed]->> setUserPrefs

'action dependencies
  initialize -[#blue]->> initializeExplore
  initialize -[#blue]->> initializeList
  initialize -[#blue]->> initializeTools
  initialize -[#blue]->> initializeUser
  initialize -[#blue]->> attemptLogout

  setToastMessage <<-[#blue]- getRecommendations
  setToastMessage <<-[#blue]- deleteItem
  setToastMessage <<-[#blue]- editListItem
  setToastMessage <<-[#blue]- readList
  setToastMessage <<-[#blue]- writeList
  setToastMessage <<-[#blue]- attemptLogin

  readList -[#blue]->> resetList
  readList -[#blue]->> updateSort

'state <-> component mapping
  'views
    V_App <<-up- currentUser
    V_App -up->> readList
    V_App <<-up- windowOpen

    V_Admin <<-up- GoTrueAuth

    V_Explore <<-up- recList
    V_Explore <<-up- recSource
    V_Explore <<-up- windowOpen

    V_Home <<-up- currentUser

    V_Import -up->> sendToastMessage
    V_Import -up->> toggleWindow

    V_Invite -up->> sendToastMessage

    V_List -up->> readList
    V_List <<-up- searchActive
    V_List <<-up- tracklist
    V_List -up->> toggleWindow
    V_List <<-up- watchlist
    V_List <<-up- windowOpen

    V_Profile <<-up- currentUser
    V_Profile -up->> updateUserAccount

    V_Recover -up->> requestPasswordRecovery

    V_Signup -up->> processInvite
    V_Signup -up->> sendToastMessage

  'app global
    C_GlobalFooter <<-up- currentUser

    C_GlobalMenu <<-up- currentUser
    C_GlobalMenu -up->> toggleWindow

    C_GlobalNav <<-up- currentUser

    C_HomeLogin -up->> attemptLogin
    C_HomeLogin -up->> initialize

    C_ModalBackdrop <<-up- windowOpen

    C_ToastMessage <<-up->> toastMessage

  'buttons
    C_BtnAddTitle -up->> toggleWindow
    C_BtnAddTitle <<-up- windowOpen

    C_BtnExploreClear -up->> initializeExplore
    C_BtnExploreClear <<-up- recSource

    C_BtnListItemControls -up->> selectEditTitle
    C_BtnListItemControls -up->> toggleWindow

    C_BtnListItemEdit -up->> selectEditTitle
    C_BtnListItemEdit -up->> toggleWindow

    C_BtnListItemRemove -up->> deleteFromSearchResults
    C_BtnListItemRemove -up->> deleteItem
    C_BtnListItemRemove -up->> initializeExplore
    C_BtnListItemRemove <<-up- recSource
    C_BtnListItemRemove <<-up- searchActive
    C_BtnListItemRemove -up->> toggleWindow
    C_BtnListItemRemove <<-up- windowOpen

    C_BtnLogout -up->> attemptLogout

    C_BtnMenu -up->> toggleWindow
    C_BtnMenu <<-up- windowOpen

  'explore
    C_ExploreSelectTitle -up->> clearRecommendations
    C_ExploreSelectTitle -up->> getRecommendations
    C_ExploreSelectTitle <<-up- recSource
    C_ExploreSelectTitle <<-up- tracklist
    C_ExploreSelectTitle -up->> updateRecSource

    C_ExploreTitleCard <<-up- recSource

  'input
    C_InputSearch <<-up- searchActive

  'list
    C_ListAddModal <<-up- functions
    C_ListAddModal -up->> toggleWindow
    C_ListAddModal -up->> toggleWriteSuccess

    C_ListAddSearchResult -up->> resetList
    C_ListAddSearchResult <<-up- searchActive
    C_ListAddSearchResult <<-up- userOptions
    C_ListAddSearchResult -up->> writeList
    C_ListAddSearchResult <<-up- writeSuccess

    C_ListEditModal -up->> clearEditTitle
    C_ListEditModal -up->> deleteItem
    C_ListEditModal -up->> editListItem
    C_ListEditModal -up->> editTitleContent
    C_ListEditModal <<-up- searchActive
    C_ListEditModal -up->> toggleWindow
    C_ListEditModal -up->> toggleWriteSuccess
    C_ListEditModal -up->> updateSearchResult
    C_ListEditModal -up->> writeList
    C_ListEditModal <<-up- writeSuccess

    C_ListItem <<-up- userOptions

    C_ListItemControls -up->> editTitleContent
    C_ListItemControls <<-up- userOptions

    C_ListItemImport <<-up- tracklist
    C_ListItemImport <<-up- watchlist
    C_ListItemImport <<-up- userOptions

    C_ListPosterModal -up->> toggleWindow

    C_ListSearch -up->> resetList
    C_ListSearch -up->> searchList

    C_ListSearchStatus -up->> resetList
    C_ListSearchStatus <<-up- tracklist
    C_ListSearchStatus <<-up- tracklistCache
    C_ListSearchStatus <<-up- watchlist
    C_ListSearchStatus <<-up- watchlistCache

    C_ListSort -up->> sortList
    C_ListSort <<-up- sortMode
    C_ListSort <<-up- tracklistSorted
    C_ListSort <<-up- userOptions
    C_ListSort <<-up- watchlistSorted

  'profile
    C_ProfileExport -up->> readList
    C_ProfileExport <<-up- tracklist
    C_ProfileExport <<-up- watchlist

    C_ProfileUserSettings <<-up- sortMode
    C_ProfileUserSettings <<-up- userOptions

@enduml